// Pokemons
export const SET_POKEMONS = "POKEMONS/SET_POKEMONS";
export const POKEMONS_FETCH_START = "POKEMONS/FETCH_START";
export const POKEMONS_FETCH_END = "POKEMONS/FETCH_END";
export const POKEMONS_SUCCESS = "POKEMONS/POKEMONS_SUCCESS";
export const POKEMONS_FAILURE = "POKEMONS/POKEMONS_FAILURE";
export const ADD_POKEMON = "POKEMON/ADD_POKEMON";
export const DELETE_POKEMON = "POKEMON/DELETE_POKEMON";

// Favorite
export const SET_FAVORITE = "FAVORITE/SET_FAVORITE";
export const DELETE_FAVORITE = "FAVORITE/DELETE_FAVORITE";
